In [35]:
import pandas as pd
import os

info = os.path.abspath('../../data/output/PHANTOM1_3/info/dicominfo.txt')
df = pd.read_csv(info, sep='\t')

In [36]:
from IPython.display import HTML

def hover(hover_color="#ffff99"):
    return dict(selector="tr:hover",
                props=[("background-color", "%s" % hover_color)])

styles = [
    hover(),
    dict(selector="th", props=[("font-size", "100%"),
                               ("text-align", "center")]),
    dict(selector="td", props=[("font-size", "80%")]),
    dict(selector="caption", props=[("caption-side", "bottom")])
]
html = (df.style.set_table_styles(styles)
          .set_caption("Hover to highlight."))
html

def magnify():
    return [dict(selector="td",
                 props=[("font-size", "2pt")]),
            dict(selector="th",
                 props=[("font-size", "10pt")]),
            dict(selector="tr:hover",
                 props=[('max-width', '50%'),
                        ('font-size', '10pt')])
]

zoom = (df.style.set_table_styles(magnify())
          .set_caption("Hover to Magnify"))
zoom